apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: 192.168.0.253:32220
  - name: redisPassword
    value: "123456"
